import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  BookOpenCheck,
  BriefcaseBusiness,
  Building2,
  ClipboardCheck,
  FileCheck2,
  FileStack,
  GraduationCap,
  HeartHandshake,
  LayoutDashboard,
  RefreshCw,
  ShieldAlert,
  ShieldCheck,
} from "lucide-react";

export const MODULE_KEYS = [
  "dashboard",
  "rams",
  "incidents",
  "inspections",
  "training",
  "legal",
  "iso",
  "documents",
  "emergency",
  "contractors",
  "change",
  "community",
  "marketplace",
] as const;

export type ModuleKey = (typeof MODULE_KEYS)[number];

export type ModuleDefinition = {
  key: ModuleKey;
  label: string;
  shortLabel: string;
  description: string;
  icon: LucideIcon;
  referencePrefix: string;
  statuses: string[];
  fields: { key: string; label: string; type: "text" | "textarea" | "number" | "select" | "date" | "datetime-local"; options?: string[]; required?: boolean; group?: string; hint?: string; condition?: { key: string; values: string[] } }[];
};

export const MODULES: ModuleDefinition[] = [
  { key: "dashboard", label: "Dashboard & Analytics", shortLabel: "Overview", description: "Calculated RAG indicators, actions and operational assurance.", icon: LayoutDashboard, referencePrefix: "KPI", statuses: ["Active"], fields: [] },
  { key: "rams", label: "Risk Management & RAMS", shortLabel: "RAMS", description: "MEEPS method statements, risk controls, reviews and approvals.", icon: FileCheck2, referencePrefix: "RAMS", statuses: ["Draft", "Submitted", "Approved", "Changes requested", "Archived"], fields: [
    { key: "assessmentType", label: "Assessment workflow", type: "select", options: ["RAMS / Method Statement", "COSHH Assessment", "Return-to-Work Plan"], required: true, group: "Workflow" },
    { key: "version", label: "Controlled version", type: "number", required: true, group: "Workflow" },
    { key: "taskDescription", label: "Task description", type: "textarea", required: true },
    { key: "location", label: "Job location", type: "text", required: true },
    { key: "materials", label: "MEEPS — Materials / substances", type: "textarea", required: true, group: "MEEPS Method", condition: { key: "assessmentType", values: ["RAMS / Method Statement"] } },
    { key: "equipment", label: "MEEPS — Equipment / plant", type: "textarea", required: true, group: "MEEPS Method", condition: { key: "assessmentType", values: ["RAMS / Method Statement"] } },
    { key: "environment", label: "MEEPS — Environment / workplace", type: "textarea", required: true, group: "MEEPS Method", condition: { key: "assessmentType", values: ["RAMS / Method Statement"] } },
    { key: "peopleCompetence", label: "MEEPS — People / competence", type: "textarea", required: true, group: "MEEPS Method", condition: { key: "assessmentType", values: ["RAMS / Method Statement"] } },
    { key: "systemSteps", label: "MEEPS — Safe system / sequence", type: "textarea", required: true, group: "MEEPS Method", condition: { key: "assessmentType", values: ["RAMS / Method Statement"] } },
    { key: "hazards", label: "Hazards identified", type: "textarea", required: true, group: "Risk Assessment" },
    { key: "controls", label: "Controls and responsible persons", type: "textarea", required: true, group: "Risk Assessment" },
    { key: "likelihood", label: "Likelihood (1-5)", type: "number", required: true },
    { key: "consequence", label: "Consequence (1-5)", type: "number", required: true },
    { key: "residualLikelihood", label: "Residual likelihood (1-5)", type: "number" },
    { key: "residualConsequence", label: "Residual consequence (1-5)", type: "number" },
    { key: "sdsUrl", label: "Safety Data Sheet URL", type: "text", required: true, group: "COSHH", condition: { key: "assessmentType", values: ["COSHH Assessment"] } },
    { key: "exposureLimits", label: "Workplace exposure limits / health controls", type: "textarea", required: true, group: "COSHH", condition: { key: "assessmentType", values: ["COSHH Assessment"] } },
    { key: "reasonableAdjustments", label: "Return-to-work reasonable adjustments", type: "textarea", required: true, group: "Occupational Health", condition: { key: "assessmentType", values: ["Return-to-Work Plan"] } },
    { key: "legalRequirements", label: "UK legal considerations", type: "textarea", group: "Review" },
    { key: "approvedBy", label: "Competent approver", type: "text" },
    { key: "reviewDate", label: "Review date", type: "date" },
    { key: "workforceAcknowledgement", label: "Workforce briefing / acknowledgement", type: "textarea", group: "Approval & Briefing" },
  ] },
  { key: "incidents", label: "Incident Management", shortLabel: "Incidents", description: "Report, investigate, analyse, act and share lessons learned.", icon: AlertTriangle, referencePrefix: "INC", statuses: ["Draft", "Submitted", "Investigating", "Actions open", "Closed"], fields: [
    { key: "eventType", label: "Event type", type: "select", options: ["Near miss", "High potential near miss", "Recordable", "Reportable", "Unsafe condition", "Environmental event"], required: true },
    { key: "location", label: "Location", type: "text", required: true },
    { key: "occurredAt", label: "Date and time occurred", type: "datetime-local", required: true },
    { key: "severity", label: "Severity", type: "select", options: ["Low", "Moderate", "Serious", "Major", "Fatal"], required: true },
    { key: "injuryType", label: "Injury / event classification", type: "text" },
    { key: "daysAwayFromWork", label: "Days away from work (DAFW)", type: "number" },
    { key: "description", label: "What happened?", type: "textarea", required: true },
    { key: "immediateAction", label: "Immediate action taken", type: "textarea", required: true },
    { key: "witnesses", label: "Witnesses and statements", type: "textarea", group: "Investigation" },
    { key: "supervisorStatement", label: "Process supervisor statement", type: "textarea", group: "Investigation" },
    { key: "linkedRiskAssessment", label: "Linked RAMS / risk assessment reference", type: "text", group: "Investigation" },
    { key: "riddor", label: "RIDDOR assessment", type: "select", options: ["Not assessed", "Not reportable", "Potentially reportable", "Reportable"], required: true },
    { key: "rootCause", label: "Guided 5 Whys / root cause conclusion", type: "textarea" },
    { key: "fishbone", label: "Fishbone factors — people, plant, process, place", type: "textarea" },
    { key: "investigationPrompts", label: "Local assistant investigation prompts", type: "textarea" },
    { key: "investigationSummary", label: "Investigation conclusion", type: "textarea" },
    { key: "correctiveActions", label: "Corrective and preventive actions", type: "textarea" },
    { key: "riddorReference", label: "RIDDOR submission reference", type: "text" },
    { key: "lessonLearnt", label: "Lesson learnt — what happened, why, learning, changes", type: "textarea", group: "Learning" },
  ] },
  { key: "inspections", label: "Inspection Management", shortLabel: "Inspections", description: "Schedule inspections, capture findings and close actions.", icon: ClipboardCheck, referencePrefix: "INSP", statuses: ["Scheduled", "In progress", "Completed", "Overdue", "Cancelled"], fields: [
    { key: "inspectionType", label: "Inspection type", type: "select", options: ["Site inspection", "Equipment pre-use", "Fire safety", "Environmental", "Welfare", "Ad hoc"], required: true },
    { key: "location", label: "Location", type: "text", required: true },
    { key: "scheduleFrequency", label: "Schedule frequency", type: "select", options: ["One-off", "Daily", "Weekly", "Monthly", "Quarterly", "Annual"], required: true },
    { key: "inspector", label: "Assigned inspector", type: "text", required: true },
    { key: "checklist", label: "Checklist items / acceptance criteria", type: "textarea", required: true },
    { key: "findings", label: "Findings", type: "textarea" },
    { key: "failedItems", label: "Failed items / defects", type: "textarea" },
    { key: "score", label: "Compliance score (%)", type: "number" },
    { key: "correctiveActions", label: "Corrective actions / close-out evidence", type: "textarea" },
    { key: "completedAt", label: "Completed date", type: "date" },
  ] },
  { key: "training", label: "Training Management", shortLabel: "Training", description: "Competence matrices, certificates, courses and expiry controls.", icon: GraduationCap, referencePrefix: "TRN", statuses: ["Assigned", "In progress", "Completed", "Expired", "Verified"], fields: [
    { key: "trainingType", label: "Training workflow", type: "select", options: ["Training Matrix Requirement", "Certificate Record", "Internal Course", "Competence Verification"], required: true },
    { key: "jobRole", label: "Job role / competence profile", type: "text", required: true },
    { key: "course", label: "Course / competence", type: "text", required: true },
    { key: "learner", label: "Learner", type: "text", required: true },
    { key: "provider", label: "Provider", type: "text" },
    { key: "issueDate", label: "Issue date", type: "date" },
    { key: "expiryDate", label: "Expiry date", type: "date" },
    { key: "courseContent", label: "Course content / learning outcomes", type: "textarea", required: true, condition: { key: "trainingType", values: ["Internal Course"] } },
    { key: "assessmentType", label: "Assessment type", type: "select", options: ["Multiple choice", "True / false", "Short answer", "Practical observation", "No assessment"], required: true, condition: { key: "trainingType", values: ["Internal Course"] } },
    { key: "passingGrade", label: "Passing grade (%)", type: "number", condition: { key: "trainingType", values: ["Internal Course"] } },
    { key: "assessmentScore", label: "Learner score (%)", type: "number", condition: { key: "trainingType", values: ["Internal Course", "Competence Verification"] } },
    { key: "verification", label: "Competence evidence / sign-off", type: "textarea", condition: { key: "trainingType", values: ["Certificate Record", "Competence Verification"] } },
    { key: "verifiedBy", label: "Manager / verifier", type: "text", condition: { key: "trainingType", values: ["Competence Verification"] } },
    { key: "certificateReference", label: "Certificate reference", type: "text" },
    { key: "recommendedMatrix", label: "Local assistant recommended training matrix", type: "textarea", group: "Planning" },
  ] },
  { key: "legal", label: "Legal Compliance Library", shortLabel: "Legal compliance", description: "UK legal register, applicability, evidence and review tracking.", icon: BookOpenCheck, referencePrefix: "LEG", statuses: ["Applicable", "Compliant", "Gap identified", "Review due", "Not applicable"], fields: [
    { key: "regulation", label: "Regulation", type: "text", required: true },
    { key: "summary", label: "Plain-English requirement", type: "textarea", required: true },
    { key: "applicability", label: "Why it applies", type: "textarea", required: true },
    { key: "evidence", label: "Compliance evidence", type: "textarea" },
    { key: "sourceUrl", label: "Official source URL", type: "text" },
    { key: "industrySector", label: "Industry sector", type: "text" },
    { key: "lastUpdated", label: "Legislation last updated", type: "date" },
    { key: "responsibleOwner", label: "Compliance owner", type: "text" },
    { key: "reviewDate", label: "Next review date", type: "date" },
  ] },
  { key: "iso", label: "Management System / ISO Suite", shortLabel: "ISO suite", description: "ISO gaps, NCRs, permits, SWOT and controlled policies.", icon: ShieldCheck, referencePrefix: "ISO", statuses: ["Open", "Evidence required", "Action in progress", "Conforming", "Closed"], fields: [
    { key: "framework", label: "Management workflow", type: "select", options: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis", "Non-conformance (NCR)", "Permit to Work", "SWOT Analysis", "Controlled Policy"], required: true },
    { key: "clause", label: "Clause / control", type: "text", required: true, condition: { key: "framework", values: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis", "Non-conformance (NCR)"] } },
    { key: "assessment", label: "Assessment", type: "textarea", required: true, condition: { key: "framework", values: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis", "Non-conformance (NCR)"] } },
    { key: "score", label: "Score (0-100)", type: "number", required: true, condition: { key: "framework", values: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis"] } },
    { key: "gap", label: "Gap / non-conformance", type: "textarea", condition: { key: "framework", values: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis", "Non-conformance (NCR)"] } },
    { key: "action", label: "Required action", type: "textarea", condition: { key: "framework", values: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis", "Non-conformance (NCR)"] } },
    { key: "permitType", label: "Permit type", type: "select", options: ["Hot Work", "Confined Space", "Working at Height", "Electrical Isolation", "Excavation", "General"], required: true, condition: { key: "framework", values: ["Permit to Work"] } },
    { key: "permitLocation", label: "Permit work location", type: "text", required: true, condition: { key: "framework", values: ["Permit to Work"] } },
    { key: "validUntil", label: "Permit valid until", type: "datetime-local", required: true, condition: { key: "framework", values: ["Permit to Work"] } },
    { key: "strengths", label: "SWOT — Strengths", type: "textarea", required: true, condition: { key: "framework", values: ["SWOT Analysis"] } },
    { key: "weaknesses", label: "SWOT — Weaknesses", type: "textarea", required: true, condition: { key: "framework", values: ["SWOT Analysis"] } },
    { key: "opportunities", label: "SWOT — Opportunities", type: "textarea", required: true, condition: { key: "framework", values: ["SWOT Analysis"] } },
    { key: "threats", label: "SWOT — Threats", type: "textarea", required: true, condition: { key: "framework", values: ["SWOT Analysis"] } },
    { key: "policyVersion", label: "Policy version", type: "text", required: true, condition: { key: "framework", values: ["Controlled Policy"] } },
    { key: "assistantRationale", label: "Local assistant scoring rationale", type: "textarea", condition: { key: "framework", values: ["ISO 45001 Gap Analysis", "ISO 14001 Gap Analysis", "ISO 9001 Gap Analysis"] } },
    { key: "evidence", label: "Conformance / close-out evidence", type: "textarea" },
  ] },
  { key: "documents", label: "Work Instructions & Documents", shortLabel: "Documents", description: "Controlled SOPs, policies, procedures and work instructions.", icon: FileStack, referencePrefix: "DOC", statuses: ["Draft", "In review", "Approved", "Published", "Obsolete"], fields: [
    { key: "documentType", label: "Document type", type: "select", options: ["SOP", "Policy", "Procedure", "Work instruction", "PMV", "Form"], required: true },
    { key: "version", label: "Version", type: "text", required: true },
    { key: "content", label: "Document content / purpose", type: "textarea", required: true },
    { key: "revisionSummary", label: "Revision summary / change history", type: "textarea", required: true },
    { key: "effectiveDate", label: "Effective date", type: "date" },
    { key: "supersedes", label: "Supersedes document / version", type: "text" },
    { key: "reviewer", label: "Reviewer / approver", type: "text" },
    { key: "reviewDate", label: "Review date", type: "date" },
  ] },
  { key: "emergency", label: "Emergency Response", shortLabel: "Emergency", description: "Muster, headcount, emergency roles, contacts and drills.", icon: ShieldAlert, referencePrefix: "EMR", statuses: ["Planned", "Active", "All clear", "Review required", "Closed"], fields: [
    { key: "responseType", label: "Emergency workflow", type: "select", options: ["Evacuation / Drill", "Muster Register", "Emergency Role", "Emergency Contact"], required: true },
    { key: "eventType", label: "Event / drill type", type: "select", options: ["Fire drill", "Evacuation", "Chemical spill", "Medical emergency", "Security incident"], required: true, condition: { key: "responseType", values: ["Evacuation / Drill"] } },
    { key: "musterPoint", label: "Muster point", type: "text", required: true, condition: { key: "responseType", values: ["Evacuation / Drill", "Muster Register", "Emergency Role"] } },
    { key: "expected", label: "Expected headcount", type: "number", required: true, condition: { key: "responseType", values: ["Evacuation / Drill", "Muster Register"] } },
    { key: "accountedFor", label: "Accounted for", type: "number", condition: { key: "responseType", values: ["Evacuation / Drill", "Muster Register"] } },
    { key: "exempt", label: "Exempt / confirmed off-site", type: "number", condition: { key: "responseType", values: ["Evacuation / Drill", "Muster Register"] } },
    { key: "unaccounted", label: "Unaccounted", type: "number", condition: { key: "responseType", values: ["Evacuation / Drill", "Muster Register"] } },
    { key: "startedAt", label: "Start time", type: "datetime-local", required: true, condition: { key: "responseType", values: ["Evacuation / Drill"] } },
    { key: "allClearAt", label: "All-clear time", type: "datetime-local", condition: { key: "responseType", values: ["Evacuation / Drill"] } },
    { key: "workerRegister", label: "Worker / visitor muster register", type: "textarea", required: true, condition: { key: "responseType", values: ["Muster Register"] } },
    { key: "roleRegistry", label: "Fire Marshals, First Aiders and IMT roles", type: "textarea", required: true, condition: { key: "responseType", values: ["Emergency Role"] } },
    { key: "emergencyContacts", label: "Emergency contacts and telephone numbers", type: "textarea", required: true, condition: { key: "responseType", values: ["Emergency Contact"] } },
    { key: "observations", label: "Observations / lessons", type: "textarea", condition: { key: "responseType", values: ["Evacuation / Drill"] } },
  ] },
  { key: "contractors", label: "Client / Contractor Management", shortLabel: "Contractors", description: "Onboarding, competence, orientations, RAMS and PTW controls.", icon: Building2, referencePrefix: "CON", statuses: ["Invited", "Onboarding", "Approved", "Restricted", "Offboarded"], fields: [
    { key: "company", label: "Contractor company", type: "text", required: true },
    { key: "contact", label: "Primary contact", type: "text", required: true },
    { key: "scope", label: "Scope of work", type: "textarea", required: true },
    { key: "competenceEvidence", label: "Competence, insurance and certification evidence", type: "textarea", required: true },
    { key: "insuranceExpiry", label: "Insurance expiry", type: "date" },
    { key: "orientation", label: "Orientation status", type: "select", options: ["Not assigned", "Assigned", "Completed"], required: true },
    { key: "ramsStatus", label: "RAMS status", type: "select", options: ["Not submitted", "Submitted", "Approved", "Rejected"], required: true },
    { key: "permitStatus", label: "PTW status", type: "select", options: ["Not required", "Required", "Issued", "Closed"], required: true },
    { key: "linkedRams", label: "Linked RAMS reference", type: "text" },
    { key: "permitReference", label: "Permit to Work reference", type: "text" },
    { key: "orientationResult", label: "Orientation result / acknowledgement", type: "textarea" },
  ] },
  { key: "change", label: "Change Management", shortLabel: "Change", description: "Assess, authorise and verify organisational or operational change.", icon: RefreshCw, referencePrefix: "MOC", statuses: ["Requested", "Assessing", "Approved", "Implementing", "Verified", "Rejected"], fields: [
    { key: "changeType", label: "Change type", type: "select", options: ["Process", "Equipment", "Organisation", "Legal", "Document", "Temporary"], required: true },
    { key: "reason", label: "Reason for change", type: "textarea", required: true },
    { key: "affectedSystems", label: "Affected people, processes, documents and equipment", type: "textarea", required: true },
    { key: "impact", label: "HSE impact assessment", type: "textarea", required: true },
    { key: "controls", label: "Controls / actions", type: "textarea", required: true },
    { key: "consultation", label: "Consultation / stakeholder review", type: "textarea" },
    { key: "approver", label: "Approver", type: "text" },
    { key: "implementationDate", label: "Implementation date", type: "date" },
    { key: "verification", label: "Post-implementation verification", type: "textarea" },
    { key: "linkedRecords", label: "Linked RAMS, documents, training or contractor references", type: "textarea" },
  ] },
  { key: "community", label: "Community & Knowledge", shortLabel: "Community", description: "Share lessons, articles, toolbox content and professional discussion.", icon: HeartHandshake, referencePrefix: "POST", statuses: ["Draft", "Published", "Flagged", "Archived"], fields: [
    { key: "contentType", label: "Content type", type: "select", options: ["Safety update", "Lesson learned", "Article", "Toolbox talk", "Discussion", "Video / podcast"], required: true },
    { key: "body", label: "Content", type: "textarea", required: true },
    { key: "topic", label: "Topic", type: "text", required: true },
    { key: "mediaUrl", label: "Media URL", type: "text" },
    { key: "sourceRecord", label: "Source incident / RAMS / inspection reference", type: "text" },
    { key: "moderationNotes", label: "Moderation / review notes", type: "textarea" },
  ] },
  { key: "marketplace", label: "Consultant Marketplace", shortLabel: "Marketplace", description: "Professional profiles, discovery, community, engagements, test escrow and two-way ratings.", icon: BriefcaseBusiness, referencePrefix: "ENG", statuses: ["Profile active", "Unavailable", "Draft", "Published", "Proposed", "Negotiating", "Funded", "Active", "Completed", "Disputed"], fields: [
    { key: "consultant", label: "Consultant / firm", type: "text", required: true },
    { key: "specialism", label: "Specialism", type: "text", required: true },
    { key: "brief", label: "Project brief", type: "textarea", required: true },
    { key: "agreedRate", label: "Agreed rate (£)", type: "number", required: true },
    { key: "milestone", label: "Current milestone", type: "text" },
    { key: "rating", label: "Rating (1-5)", type: "number" },
    { key: "completionEvidence", label: "Milestone / completion evidence", type: "textarea" },
  ] },
];

export const MODULE_MAP = Object.fromEntries(MODULES.map((module) => [module.key, module])) as Record<ModuleKey, ModuleDefinition>;

export function isModuleKey(value: string): value is ModuleKey {
  return (MODULE_KEYS as readonly string[]).includes(value);
}

export const WRITABLE_ROLES = ["SuperAdmin", "CompanyAdmin", "Manager", "Supervisor", "FrontLineEmployee", "Consultant"] as const;
